version: '3.1'

services:
  web:
    image: maksredka/flaskproj:v4
    build: .
    environment:
      DB_URL: postgresql+psycopg2://postgres:password@db:5432/postgres
    ports: 
      - '8000:8000'
    volumes:
      - './statik:/images'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
  static_volume:
    